"""users table

Revision ID: 1d04b91cd243
Revises: 6d2168f3a801
Create Date: 2021-04-03 05:23:14.823168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d04b91cd243'
down_revision = '6d2168f3a801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EMPLOYEE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EMPLOYEE',
    sa.Column('FIRST_NAME', mysql.CHAR(length=20), nullable=False),
    sa.Column('LAST_NAME', mysql.CHAR(length=20), nullable=True),
    sa.Column('AGE', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SEX', mysql.CHAR(length=1), nullable=True),
    sa.Column('INCOME', mysql.FLOAT(), nullable=True),
    mysql_collate=u'utf8mb4_0900_ai_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
