"""empty message

Revision ID: 3590c916d61c
Revises: 6fef5bfdb935
Create Date: 2021-04-21 02:58:16.274095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3590c916d61c'
down_revision = '6fef5bfdb935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('BloodPressure', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('ChestPain', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heart_disease_prediction', 'ChestPain')
    op.drop_column('heart_disease_prediction', 'BloodPressure')
    # ### end Alembic commands ###
