"""empty message

Revision ID: 3e26756d5fc0
Revises: 3590c916d61c
Create Date: 2021-04-21 03:01:23.539187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e26756d5fc0'
down_revision = '3590c916d61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('prediction', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'heart_disease_prediction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heart_disease_prediction', type_='foreignkey')
    op.drop_column('heart_disease_prediction', 'user_id')
    op.drop_column('heart_disease_prediction', 'prediction')
    # ### end Alembic commands ###
