"""empty message

Revision ID: 44ea50da857b
Revises: 4ed60e84cf8f
Create Date: 2021-04-21 01:55:38.410664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ea50da857b'
down_revision = '4ed60e84cf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('BloodPressure', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('ChestPain', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('ElectrocardiographicResults', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('ExerciseInducedAngina', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('Gender', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('MajorVesselsNo', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('MaxHeartRate', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('STdepression', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('Thalassemia', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('prediction', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'heart_disease_prediction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heart_disease_prediction', type_='foreignkey')
    op.drop_column('heart_disease_prediction', 'user_id')
    op.drop_column('heart_disease_prediction', 'prediction')
    op.drop_column('heart_disease_prediction', 'Thalassemia')
    op.drop_column('heart_disease_prediction', 'STdepression')
    op.drop_column('heart_disease_prediction', 'MaxHeartRate')
    op.drop_column('heart_disease_prediction', 'MajorVesselsNo')
    op.drop_column('heart_disease_prediction', 'Gender')
    op.drop_column('heart_disease_prediction', 'ExerciseInducedAngina')
    op.drop_column('heart_disease_prediction', 'ElectrocardiographicResults')
    op.drop_column('heart_disease_prediction', 'ChestPain')
    op.drop_column('heart_disease_prediction', 'BloodPressure')
    # ### end Alembic commands ###
