"""empty message

Revision ID: 5175ef9faf03
Revises: cf52a16d1bed
Create Date: 2021-04-27 16:55:40.146146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5175ef9faf03'
down_revision = 'cf52a16d1bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liver_disease', sa.Column('prediction', sa.Integer(), nullable=True))
    op.add_column('liver_disease', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'liver_disease', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'liver_disease', type_='foreignkey')
    op.drop_column('liver_disease', 'user_id')
    op.drop_column('liver_disease', 'prediction')
    # ### end Alembic commands ###
