"""empty message

Revision ID: 705ab4f066b6
Revises: e1ec6f54d05e
Create Date: 2021-04-25 20:52:41.527260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705ab4f066b6'
down_revision = 'e1ec6f54d05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pneumonia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pneumonia_timestamp'), 'pneumonia', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pneumonia_timestamp'), table_name='pneumonia')
    op.drop_table('pneumonia')
    # ### end Alembic commands ###
