"""empty message

Revision ID: 99a4afeebd6e
Revises: ec1f485df1ea
Create Date: 2021-04-21 01:04:04.028987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a4afeebd6e'
down_revision = 'ec1f485df1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heart_disease_prediction', 'ExercisePeakSlope')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('ExercisePeakSlope', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
