"""empty message

Revision ID: b41145eeece5
Revises: 02d4bebde76c
Create Date: 2021-04-05 08:53:14.623150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b41145eeece5'
down_revision = '02d4bebde76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ssn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ssn', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
