"""empty message

Revision ID: b79b6f937210
Revises: d0ed70075fa7
Create Date: 2021-04-21 04:05:08.899525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b6f937210'
down_revision = 'd0ed70075fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_heart_disease_prediction_timestamp'), 'heart_disease_prediction', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heart_disease_prediction_timestamp'), table_name='heart_disease_prediction')
    op.drop_column('heart_disease_prediction', 'timestamp')
    # ### end Alembic commands ###
