"""empty message

Revision ID: cf52a16d1bed
Revises: 705ab4f066b6
Create Date: 2021-04-27 00:22:14.805557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf52a16d1bed'
down_revision = '705ab4f066b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liver_disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.Integer(), nullable=True),
    sa.Column('Total_Bilirubin', sa.Float(precision=9), nullable=True),
    sa.Column('Direct_Bilirubin', sa.Float(precision=9), nullable=True),
    sa.Column('Alkaline_Phosphotase', sa.Integer(), nullable=True),
    sa.Column('Alamine_Aminotransferase', sa.Integer(), nullable=True),
    sa.Column('Aspartate_Aminotransferase', sa.Integer(), nullable=True),
    sa.Column('Total_Protiens', sa.String(length=128), nullable=True),
    sa.Column('Albumin', sa.String(length=128), nullable=True),
    sa.Column('Albumin_and_Globulin_Ratio', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liver_disease_timestamp'), 'liver_disease', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liver_disease_timestamp'), table_name='liver_disease')
    op.drop_table('liver_disease')
    # ### end Alembic commands ###
