"""empty message

Revision ID: d0e3df313364
Revises: 5175ef9faf03
Create Date: 2021-04-27 18:32:43.738155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e3df313364'
down_revision = '5175ef9faf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('Symptom1', sa.String(length=128), nullable=True),
    sa.Column('Symptom2', sa.String(length=128), nullable=True),
    sa.Column('Symptom3', sa.String(length=128), nullable=True),
    sa.Column('Symptom4', sa.String(length=128), nullable=True),
    sa.Column('Symptom5', sa.String(length=128), nullable=True),
    sa.Column('prediction', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_disease_timestamp'), 'general_disease', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_general_disease_timestamp'), table_name='general_disease')
    op.drop_table('general_disease')
    # ### end Alembic commands ###
