"""empty message

Revision ID: d0ed70075fa7
Revises: 3e26756d5fc0
Create Date: 2021-04-21 03:22:26.196145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ed70075fa7'
down_revision = '3e26756d5fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heart_disease_prediction', sa.Column('ElectrocardiographicResults', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('ExerciseInducedAngina', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('MajorVesselsNo', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('MaxHeartRate', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('STdepression', sa.Integer(), nullable=True))
    op.add_column('heart_disease_prediction', sa.Column('Thalassemia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heart_disease_prediction', 'Thalassemia')
    op.drop_column('heart_disease_prediction', 'STdepression')
    op.drop_column('heart_disease_prediction', 'MaxHeartRate')
    op.drop_column('heart_disease_prediction', 'MajorVesselsNo')
    op.drop_column('heart_disease_prediction', 'ExerciseInducedAngina')
    op.drop_column('heart_disease_prediction', 'ElectrocardiographicResults')
    # ### end Alembic commands ###
