"""users table

Revision ID: e53926297f2d
Revises: b41145eeece5
Create Date: 2021-04-10 05:46:56.619685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53926297f2d'
down_revision = 'b41145eeece5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bp', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('consent', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('diabetes', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('privacy', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('smoke', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms')
    op.drop_column('user', 'smoke')
    op.drop_column('user', 'privacy')
    op.drop_column('user', 'diabetes')
    op.drop_column('user', 'consent')
    op.drop_column('user', 'bp')
    # ### end Alembic commands ###
